export default {
  today: 'TODAY',
  tomorrow: 'TOMORROW',
  yesterday: 'YESTERDAY',
  spot: 'SPOT-T+2',
  startOfPreviousYear: 'START_OF_PREVIOUS_YEAR',
  endOfPreviousYear: 'END_OF_PREVIOUS-YEAR',
  startOfCurrentYear: 'START_OF_CURRENT_YEAR',
  endOfCurrentYear: 'END_OF_CURRENT_YEAR',
  startOfPreviousMonth: 'START_OF_PREVIOUS_MONTH',
  endOfPreviousMonth: 'END_OF_PREVIOUS_MONTH',
  startOfCurrentMonth: 'START_OF_CURRENT_MONTH',
  endOfCurrentMonth: 'END_OF_CURRENT_MONTH',
  startOfPreviousWeek: 'START_OF_PREVIOUS_WEEK',
  endOfPreviousWeek: 'END_OF_PREVIOUS_WEEK',
  startOfCurrentWeek: 'START_OF_CURRENT_WEEK',
  endOfCurrentWeek: 'END_OF_CURRENT_WEEK',
  startOfNextWeek: 'START_OF_NEXT_WEEK',
  endOfNextWeek: 'END_OF_NEXT_WEEK',
  startOfNextMonth: 'START_OF_NEXT_MONTH',
  endOfNextMonth: 'END_OF_NEXT_MONTH',
  startOfNextYear: 'START_OF_NEXT_YEAR',
  endOfNextYear: 'END_OF_NEXT_YEAR',
};
